<?php

// Misc Language Pack for Discuz! Version 1.0.0
// Translated by Crossday
//ENGLISH DISCUZ!7.2 TRANSLATE BY COOBY http://www.imcrp.com
$language = array
(
	'discuz_lang' => 'misc',

	'anonymous' => 'Anonymous',

	'post_hidden' => '**** Hidden by Author ****',
	'post_banned' => '**** Author has been banned or deleted ****',
	'post_single_banned' => '**** Post Banned ****',
        'message_ishidden_hiddenreplies' => 'Just the author can read',
	'post_reply_quote' => '$thaquote[author] Posted at $time',
	'post_edit' => '[i=s] Post Last Edited by $editor at $edittime [/i]\n\n',
	'post_edit_regexp' => '/^\[i=s\] Post Last edited by .*? at .*? \[\/i\]\n\n/s',
	'post_reply' => 'Reply',
	'post_thread' => '\'s Thread',

	'price' => 'Price',
	'pay_view' => 'Record',
	'attachment_buy' => 'Buy',

	'post_trade_yuan' => 'Money',
	'post_trade_seller' => 'Seller',
	'post_trade_name' => 'Name',
	'post_trade_price' => 'Price',
	'post_trade_quality' => 'Quality',
	'post_trade_locus' => 'Location',
	'post_trade_transport_type' => 'Transport Type',
	'post_trade_transport_seller' => 'Seller will afford the postage',
	'post_trade_transport_buyer' => 'Buyer will afford the postage',
	'post_trade_transport_mail' => 'Mail',
	'post_trade_transport_express' => 'Express',
	'post_trade_transport_virtual' => 'Virtual item or no delivery required',
	'post_trade_transport_physical' => 'Pay to distribution company after buyer received goods',
	'post_trade_locus' => 'Location',
	'post_trade_description' => 'Description',
	'post_trade_pm_subject' => '[Bargain]',
	'post_trade_pm_buynum' => 'Quantity',
	'post_trade_pm_wishprice' => 'Expectable price is',
	'post_trade_pm_reason' => 'Reason',
	'payment_unit' => 'Money',

	'attach' => 'Attachment',
	'attach_pay' => 'Sales Attachment',
	'attach_credits_policy' => 'View credits policy',
	'attach_img' => 'Image Attachment',
	'attach_readperm' => 'Read Permission',
	'attach_img_zoom' => 'Click here to open new windows\\nCTRL+Mouse wheel to zoom in/out',
	'attach_img_thumb' => 'Click here to view full image in new windows',
	'attach_downloads' => 'Downloaded count',

	'post_trade_transport' => 'Transportation Fee',
	'post_trade_transport_mail' => 'Mail',
	'post_trade_quality' => 'Quality',
	'post_trade_quality_new' => 'New',
	'post_trade_quality_secondhand' => 'Old',

	'trade_unstart' => '<font color="gray">Waiting for process</font>',
	'trade_waitbuyerpay' => 'Waitting for buyer to pay',
	'trade_waitsellerconfirm' => 'Waiting for seller confirmation',
	'trade_sysconfirmpay' => 'Waitting for system, please do not ship goods now',
	'trade_waitsellersend' => 'waiting for seller to ship goods',
	'trade_waitbuyerconfirm' => 'Waiting for seller confirmation',
	'trade_syspayseller' => 'Waitting for system to pay the seller',
	'trade_finished' => '<font color="green">Trade successfully finished</font>',
	'trade_closed' => '<font color="gray">Trade closed(unfinished)</font>',
	'trade_waitselleragree'  => 'Waitting for seller to approve refund',
	'trade_sellerrefusebuyer' => 'Seller refused, waitting for buyer to change the terms',
	'trade_waitbuyerreturn' => 'Seller approved refund, waitting for buyer to return goods',
	'trade_waitsellerconfirmgoods' => 'Waitting for seller confirmation',
	'trade_waitalipayrefund' => 'Waitting for Alipay to refund',
	'trade_alipaycheck' => 'Waitting for Alipay process',
	'trade_overedrefund' => 'Refund overed',
	'trade_refundsuccess' => '<font color="green">Successfully refunded</font>',
	'trade_refundclosed' => '<font color="green">Refund closed</font>',

	'trade_offline_1' => 'Effective transaction.',
	'trade_offline_4' => 'I have paid and waiting for goods delivery.',
	'trade_offline_5' => 'I have delivered.',
	'trade_offline_7' => 'I have received, transaction successful.',
	'trade_offline_8' => 'Cancel this transaction.',
	'trade_offline_10' => 'I want to return, waiting for the sellers agreed to refund.',
	'trade_offline_11' => 'The seller refused to refund.',
	'trade_offline_12' => 'Sellers agreed to refund.',
	'trade_offline_13' => 'I have returned, awaiting seller to receive goods.',
	'trade_offline_17' => 'Sellers received returns, refunded.',

	'trade_message_4' => 'May input payments and bank account information.',
	'trade_message_5' => 'May input shipments, invoices, and other information.',
	'trade_message_13' => 'May input shipments, invoices, and other information.',
	
	'reportpost_your' => 'You',
	'reportpost_recommend' => ' Recommend',
	'reportpost_delate' => ' Report',
	'reportpost_post' => ' Post',
	'reportpost_yourpost' => 'Your Post',
	'reportpost_thread' => ' Thread',
	'reportpost_yourthread' => 'Your Thread',
	'reportpost_say' => 'Say',

	'credit_payment' => 'Recharge credits',
	'credit_forum_payment' => 'Recharge forum Credits',
	'credit_forum_royalty' => 'Transaction fee',

        'formulaperm_regdate' => 'Register date',
	'formulaperm_regday' => 'Register day',
	'formulaperm_regip' => 'Register IP',
	'formulaperm_lastip' => 'Last loginIP',
	'formulaperm_buyercredit' => 'buyer credit estimated',
	'formulaperm_sellercredit' => 'Seller credit estimated',
	'formulaperm_digestposts' => 'Digests',
	'formulaperm_posts' => 'Posts',
	'formulaperm_threads' => 'Thread',
	'formulaperm_oltime' => 'Onlime Time(Hour)',
	'formulaperm_pageviews' => 'Page views',
	'formulaperm_and' => 'and',
	'formulaperm_or' => 'or',
	'formulaperm_extcredits' => 'User-defined credits',

	'login_normal_mode' => 'Normal Mode',
	'login_switch_invisible_mode' => 'Switch to Invisible Mode',
	'login_switch_normal_mode' => 'Switch to Normal Mode',
	'login_invisible_mode' => 'Invisible Mode',

	'eccredit_explain' => 'Explain',

	'google_site_0' => 'Search Web',
	'google_site_1' => 'Search Site',
	'google_sa' => 'Search',

	'modcp_logs_action_home' => 'CP home',
	'modcp_logs_action_announcements' => 'Announce Manage',
	'modcp_logs_action_members' => 'Member Moderate',
	'modcp_logs_action_forumaccess' => 'User Permission',
	'modcp_logs_action_forums' => 'Board Setting',
	'modcp_logs_action_report' => 'User Report',
	'modcp_logs_action_moderate' => 'Moderate Thread',
	'modcp_logs_action_login' => 'Login',

	'uch_selectalbum' => 'Select album',
	'uch_noalbum' => 'You dont have albums',
	'click_here' => 'click here',
	'uch_createalbum' => 'Bar to create your own album!',

	'pm_from' => 'From',
	'pm_to' => 'To',
	'pm_date' => 'Date',

	'share_message' => 'Hello! I see a Thread in $bbname, I think it is Valuable. \\n\\n$thread[subject]\\nURL $threadurl\\n\\nHope you like it.',

	'week_0' => 'Sun',
	'week_1' => 'Mon',
	'week_2' => 'Tue',
	'week_3' => 'Wed',
	'week_4' => 'Thu',
	'week_5' => 'Fri',
	'week_6' => 'Sat',
	
	'notice_actor' => 'etc. $actorcount person',

	'perms_allowvisit' => 'Visit Forum',
	'perms_readaccess' => 'Read Permission',
	'perms_allowviewpro' => 'View User Infomation',
	'perms_allowinvisible' => 'Invisible',
	'perms_allowsearch' => 'Search',
	'perms_allownickname' => 'Use NickName',
	'perms_allowcstatus' => 'Custom Status',
	'perms_allowpost' => 'Post Thread',
	'perms_allowreply' => 'Post Reply',
	'perms_allowpostpoll' => 'Post Poll',
	'perms_allowvote' => 'Join Poll',
	'perms_allowpostreward' => 'Join Reward',
	'perms_allowpostactivity' => 'Join Activity',
	'perms_allowpostdebate' => 'Join Debate',
	'perms_allowposttrade' => 'Join Trade',
	'perms_maxsigsize' => 'Max Signature',
	'perms_allowsigbbcode' => 'Use Discuz! Code in Signature',
	'perms_allowsigimgcode' => 'Use [img] Code in signature',
	'perms_maxbiosize' => 'Max selfintroduce',
	'perms_allowrecommend' => 'Thread Recommend',
	'perms_allowbiobbcode' => 'Use Discuz! Code in selfintroduce ',
	'perms_allowbioimgcode' => 'Use [img] code in selfintroduce',
	'perms_allowgetattach' => 'Download/View Attachments',
	'perms_allowpostattach' => 'Upload attachment',
	'perms_allowsetattachperm' => 'Use [img] code in selfintroduce',
	'perms_maxattachsize' => 'Max attachments size',
	'perms_maxsizeperday' => 'Max attachments size per day',
	'perms_allowbioimgcode' => 'Use [img] code in selfintroduce',
	'perms_attachextensions' => 'Attachment Type',
	'perms_allowstickthread' => 'Stick Thread',
	'perms_allowdigestthread' => 'Digest Thread',
	'perms_allowstickthread_value' => 'Stick',
	'perms_allowdigestthread_value' => 'Digest',
	'perms_allowbumpthread' => 'Bump thread',
	'perms_allowhighlightthread' => 'Hightlight Thread',
	'perms_allowrecommendthread' => 'Recommend Thread',
	'perms_allowstampthread' => 'Stamp Thread',
	'perms_allowclosethread' => 'Close Thread',
	'perms_allowmovethread' => 'Move Thread',
	'perms_allowedittypethread' => 'Edit thread type',
	'perms_allowcopythread' => 'Copy thread',
	'perms_allowmergethread' => 'Merge thread',
	'perms_allowsplitthread' => 'Split thread',
	'perms_allowrepairthread' => 'Repair thread',
	'perms_allowrefund' => 'Refund',
	'perms_alloweditpoll' => 'Edit Poll',
	'perms_allowremovereward' => 'Remove reward',
	'perms_alloweditactivity' => 'Edit activity ',
	'perms_allowedittrade' => 'Edit Goods',
	'perms_alloweditpost' => 'Edit Post',
	'perms_allowwarnpost' => 'Warning post',
	'perms_allowbanpost' => 'Ban post',
	'perms_allowdelpost' => 'Delete Post',
	'perms_allowviewreport' => 'View user report',
	'perms_allowmodpost' => 'Audit Post',
	'perms_allowmoduser' => 'Audit User',
	'perms_allowbanuser' => 'Ban User',
	'perms_allowbanip' => 'Ban IP',
	'perms_allowedituser' => 'Edit User',
	'perms_allowmassprune' => 'Batch delete Post',
	'perms_allowpostannounce' => 'Post announce',
	'perms_disablepostctrl' => 'Post without limits',
	'perms_allowviewip' => 'View IP',

);

?>