<?php

// Message Pack for Discuz! WAP Version 1.0.0
// Created by Crossday
//ENGLISH DISCUZ!7.2 TRANSLATE BY COOBY http://www.imcrp.com
$lang = array
(

	'username' => 'UserName',
    'uid' => 'UID',
	'password' => 'Password',
	'submit' => 'Submit',
	'page' => 'Page',
	'replies' => 'Replies',
	'views' => 'Views',
	'reply' => 'Reply',
	'delete' => 'Delete',
	'anonymous' => 'Anonymous',
	'forum' => 'Forum',
	'from' => 'From:',
	'type' => 'Type:',
	'subject' => 'Subject:',
	'message' => 'Message:',
	'home_page' => 'HOME',
	'last_page' => 'Last Page',
	'next_page' => 'Next Page',
	'end_page' => 'End Page',
	'turn_page' => 'Turn Page',
	'next_thread' => 'Next Thread',
	'last_thread' => 'Last Thread',
	'end' => 'End',
	'unread' => 'Unread',
	'sub_forums' => 'Sub Forums',
	'email'	=> 'Email',
	'more'	=> 'More',
	'search' => 'Search',
	'digest' => 'Digest',
	'reload' => 'Refresh',
	'author' => 'Author:',
	'dateline' => 'Dateline:',
	'return' => 'Return',
	'keywords' => 'Keywords',

	'not_loggedin' => 'Please Login',
	'wap_disabled' => 'WAP Disabled',
	'board_closed' => 'Forum Closed',
	'undefined_action' => 'Undefined Action',

	'home_online' => 'Online:',
	'home_members' => 'Members',
	'home_newpm' => 'PMs',
	'home_forums' => 'Forums',
	'home_tools' => 'Tools',
	'home_newthreads' => 'View New Thread',

	'login' => 'Login',
	'login_username' => 'UserName/UID',
	'login_succeed' => '{$discuz_user}Login Succeed',
	'login_strike' => 'You have entered the wrong password for the fifth time, please wait 15 minutes before trying again',
	'login_invalid' => 'Invalid username or password, you may have a maximum of 5 attempts. If you don\'t have an account, please visit {$boardurl}register.php to register and try again',
	'logout' => 'Logout',
	'logout_succeed' => 'Logout succeed',
	'security_question' => 'Security Question',
	'security_answer' => 'Answer',
	'security_question_0' => 'None',
	'security_question_1' => 'Mother\'s Name',
	'security_question_2' => 'Grandpa\'s Name',
	'security_question_3' => 'My Birth Place',
	'security_question_4' => 'One of My teacher\'s Name',
	'security_question_5' => 'My lover\'s name',
	'security_question_6' => 'My Favorite Resteraunt',
	'security_question_7' => 'My Passport\'s Number',

	'register' => 'Register',
	'register_username' => 'UserName',
	'register_disable' => 'Register by WAP is unavailable',
        'register_reason' => 'Reason',
	'register_ctrl' => 'Sorry, you can only register one account within $regctrl hour',
	'register_flood_ctrl' => 'Sorry, the same IP only can try $regfloodctrl times to register 24hours, please return.',
	'register_manual_verify' => 'Thank you for your register. Your account will be checked by Administrator, Now you will be redirect to User CP',
	'register_succeed' => 'Thank you for your register',
	'activation_disable' => 'Activation through WAP is not allowed in this forum',
	'register_activation_message' => 'Sorry, the UserName you input \"$username\" is already exists, Please login and activate it.<br /><a href=\"index.php?action=login\">Login</a>',

	'profile_username_duplicate' => 'UserName is Already Exist',
	'profile_email_duplicate' => 'Email Address Already Exist',
	'profile_username_illegal' => 'Some characters in your name is Forbidden',
	'profile_username_protect' => 'Some characters in your name is Forbidden',
	'profile_email_illegal' => 'Email is illegal, please Reset',
	'profile_email_domain_illegal' => 'This Email service is not allowed in our forum, please input other kind of Email',

	'fav_add_succeed' => 'Add Favorites Successfully, Please Return',
	'fav_existence' => 'You have already added this to your Favorites, Please Return',

	'goto_last_nonexistence' => 'This is the first topic',
	'goto_next_nonexistence' => 'This is the last topic',

	'forum_thread_sticky' => '[Sticky]',
	'forum_thread_digest' => '[Digest]',
	'forum_nopermission' => 'You don\'t have permission to visit this forum',
	'forum_nonexistence' => 'Specified forum doesn\'t exist',
	'forum_list' => 'Thread List',
	'forum_sublist' => 'SubForum List',

	'my' => 'My',
	'my_uid' => 'UID:',
	'my_username' => 'Username:',
	'my_gender' => 'Gender:',
	'my_bday' => 'Birthday:',
	'my_location' => 'From:',
	'my_bio' => 'About Me:',
	'my_phone' => 'My Phone',
	'my_favorites' => 'My Favorites',
	'my_addfav' => 'Add Favorite',
	'my_nonexistence' => 'The member is unavailable.',
	'my_male' => 'Male',
	'my_female' => 'Female',
	'my_secrecy' => 'Secret',
	'my_threads' => 'My topics',
	'my_replies' => 'My replies',
	'my_fav_thread' => 'My favorite topics.',
	'my_fav_forum' => 'My favorite forums.',

	'thread_nopermission' => 'Sorry, you do not have the enough authority.',
	'thread_nonexistence' => 'Sorry, the topic is unavailable.',
	'thread_replylist' => 'Reply list',
	'thread_reply' => 'Reply topic:',
	'thread_quickreply' => 'Lightning Reply',
        'thread_banned' => 'Post was banned!',
	
	'post_reply' => 'Reply',
	'post_new' => 'New Post',
	'post_sm_isnull' => 'Error, you need input both of title and contents.',
	'post_subject_toolong' => 'Error:The max-length of title is 80 characters.',
	'post_message_toolong' => 'Error:The max-length of contents is {$maxpostsize}.',
	'post_message_tooshort' => 'Error:The min-length of contents is {$minpostsize}',
	'post_type_isnull' => 'Error, please select the category of topic.',
	'post_flood_ctrl' => 'Two posts are limited in {$floodctrl} s',
	'post_mod_succeed' => 'Successful',
	'post_mod_forward' => 'Go to current forum.',
	'post_thread_closed' => 'The topic is unavailable,now.',
	'post_thread_closed_by_dateline' => 'The topic is unavailable,now.',
	'post_thread_closed_by_lastpost' => 'The topic is unavailable,now.',
	'post_newbie_span' => 'You can post new topic only after {$newbiespan} hours.',
	'post_hide_nopermission' => 'Sorry, you do not have the enough authority to use [hide]code.',
	'post_newthread_nopermission' => 'Sorry, you do not have the enough authority to post new topic.',
	'post_newthread_succeed' => 'Successful:<br /><a href=\"index.php?action=forum&amp;fid=$fid\">Return</a>',
	'post_newthread_forward' => 'View topics',
	'post_newreply_nopermission' => 'Sorry, you do not have the enough authority to reply in this forum.',
	'post_newreply_succeed' => 'Successful:<br /><a href=\"index.php?action=forum&amp;fid=$fid\">Return</a>',
	'post_newreply_forward' => 'View replies',

        'message_banned' => 'Tip: <em>Author is Banned or Account deleted</em>',
	'message_single_banned' => 'Tip: <em>The quote has been in administrator or moderator shield</em>',
	'admin_message_banned' => 'Tip: <em>Author is prohibited or remove content automatically shielding, only the administrator can view it</em>',
	'admin_message_single_banned' => 'Tips: <em>The quote has been an administrator or moderator shield, only the administrator can view it</em>',

	'profile_username_toolang' => 'Error : The max-length of name is 15 characters.',
	'profile_username_tooshort' => 'Error : The min-length of name is 3 characters.',
	'profile_passwd_notmatch' => 'The password confirmation you entered was incorrect ',
		
	'profile_passwd_illegal' => 'The password you entered was incorrect.',
	'profile_email_verify' => 'The email of confirmation was send successfully; if you can not receive the system email please check your email again.',

	'pm' => 'PM',
	'pm_home' => 'PM Home',
	'pm_list' => 'Message List',
	'pm_unread' => 'Unread Message ',
	'pm_all' => 'All Message',
	'pm_send' => 'Send Message',
	'pm_to' => 'To',
	'pm_delete_all' => 'Delete all viewed Message',
	'pm_flood_ctrl' => 'Two posts are limited in {$floodctrl}s',
	'pm_delete_confirm' => 'Confirm:Delete all read Message',

	'pm_sm_isnull' => 'Error: No title or contents.',
	'pm_nonexistence' => 'Unavailable short-message',
	'pm_send_nonexistence' => 'Unavailable Receiver',
	'pm_send_ignore' => 'Receiver will ignore your short-message.',
	'pm_send_succeed' => 'Send successfully.',
	'pm_delete_succeed' => 'Delete successfully.',

	'return_thread' => 'Return to the topic',
	'return_forum' => 'Return to the forum',

	'stats' => 'Statistics',
	'stats_threads' => 'Topics',
	'stats_posts' => 'Posts',
	'stats_members' => 'Members',
	
	'search' => 'Search',
	'search_result' => 'Results',
	'search_invalid' => 'Please input what you want to search.',
	'search_ctrl' => 'Sorry£¬you can only search one time within $searchctrl s .',
	'search_id_invalid' => 'No suitable matches were found.',
	'search_group_nopermission' => 'No suitable matches were found.',

	'goto' => 'Go to WAP',
	'wap_submit_invalid' => 'Confirmation info is invalid',
	'post_hide_reply_hidden' => 'Hidden',
	'register_invite' => 'Forum open invitation, please register by WWW',

	'message_ishidden_hiddenreplies' => 'The post just can read by author',

);

?>